spring.data.mongodb.uri=mongodb://localhost:27017/cloudshare

server.servlet.context-path=/api/v1.0

#spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://settling-asp-16.clerk.accounts.dev
clerk.jwks-url=https://settling-asp-16.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=0Y1A3+9BKRax+0pD7dExdm8Q14ZfqcFM

#file upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

#razorpay configuration
razorpay.key.id=ADD_YOUR_RAZORPAY_KEY
razorpay.key.secret=ADD_YOUR_RAZORPAY_SECRET